### ISSUE TITLE
Opinion and suggestions

### ISSUE THREAD

**Issue by NoraYashika** [crwntec/db-live-monitor#3]
Hiya @crwntec,
I saw your application and was immediately baffled. Since I will move to Germany soon, it'll come in handy...
You said you are all ears for suggestions and I have a few.
<ol>
  <li>Language support for different languages</li>
  <li>route planner (will need some explanation, I'll do that below</li>
  <li>Accessibility features for people with disabilities</li>
  <li>Amenities list, like does the train provide an internet connection or like that, if possible</li>
</ol>
<h3> route planner?? </h3>
I mean by that an option to select a series of stops, in order to chain them together, for example Berlin to Frankfurt with a stop at Magdeburg. The user would select "Berlin, Madgeburg, Frankfurt" (just as an example) in a seperate (prob'ly, i dunno?) route selection window or something. I hope you know, what I mean.

I hope there are some good ideas.

anyways, hang in there and get the 400h. 
TTYS
 ~Nora

**Comment by crwntec** [comment]
Hey Nora,
I really appreciate your interest in this project. Regarding your suggestions I have a few things to say:

## 1. Language support
Implementing this would be fairly easy because there are librarys for that and HAFAS natively supports different languages for hints and remarks
## 2. Route planner
Route planning is also supported by the [HAFAS client](https://github.com/public-transport/hafas-client/blob/main/docs/journeys.md) but involves much more works as it requires building a whole new page for it. And the problem with adding a new page is the lack of navigation. I currently don´t have any kind of navigation bar that would allow you to switch between departure and route mode and the UI isn´t really designed for that either. But if you have any suggestions on where to implement something like that, feel free to let me know.
## 3. Accessibility
I don´t have any idea on how to make something like this and I doubt that there are many people that would profit from it, but if I have time I´ll look into it
## 4. Amenities
This is something I had on my mind since I started working on the train order feature, because the API also has information on that, but I kinda forgot about it and moved on, because in my experience, almost all trains from DB Fernverkehr now have functioning wifi. However I´m probably going to implement it in a feature version.

Thanks for you interest!
crwntec

**Comment by crwntec** [comment]
Update 4.5.0
You should now be able to change the applications language via the settings menu. However I could only translate about 90% because IRIS encodes its messages with numbers and I have a JSON file to parse those and as I´ve not translated this file yet you´d still need a translator to find out why a train is delayed for example.

crwntec

Btw thanks for the star :)

**Comment by NoraYashika** [comment]
Hey @crwntec,
thanks for adding in the translation. If you want, I can help you translate it. I thought of a section basically between frontend and backend. In this section is an API that catches everything, you want to display and translates it to a selected language.
Let me know what you think and if it is okay for you, I'd help you to  make this program and tell you where to integrate it.

Let me know and TTYS, 
~ Nora

**Comment by crwntec** [comment]
That would be awesome!

**Comment by NoraYashika** [comment]
Hello again, 
should I do it in a specific language? I would do it in C/C++ for speed and efficiency reasons and output it into a json file. It would need some implementation work on both frontend and backend but maybe I could even use the system I am making for my repo  <a href = "https://github.com/NoraYashika/QORA-AI">"QORA AI"</a>. Even though it requires a certain amount of work, it would be the most efficient way and while I am working on my AIs translation system, I should just need to translate it to your desired language. It doesn't need to be C++, it could also be, i. e.: JavaScript, but keep in mind, that I need to learn the language, depending on your choice.
~Nora

**Comment by crwntec** [comment]
Hi,
What I need is a translated messageCategories.json file so that I can switch between both files based on the selected language. So a simple program that translates all of that while keeping the structure would be really useful. I don't mind if it's in C or C++. Thanks in advance 👍
crwntec
